os: linux
dist: bionic
language: cpp

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.25.4

cache:
  directories:
    - build
    - build/release
    - build/test_release

stages:
  - compile
  - test

before_script:
  - docker-compose up -d

jobs:
  include:
    - stage: compile
      name: "Compile for TXT Controller"
      script:
        - docker exec -it txt_controller_cross_compiler bash -c 'cd /workspace/build/release ; cmake -G "Unix Makefiles" -DBUILD_FOR_CONTROLLER=ON -DCMAKE_BUILD_TYPE=Release /workspace'
        - docker exec -it txt_controller_cross_compiler bash -c 'cd /workspace/build/release ; cmake --build .'
    - name: "Compile Tests"
      script:
        - docker exec -it txt_controller_cross_compiler bash -c 'cd /workspace/build/test_release ; cmake -G "Unix Makefiles" -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release /workspace'
        - docker exec -it txt_controller_cross_compiler bash -c 'cd /workspace/build/test_release ; cmake --build .'
    - stage: test
      name: "Execute Unit Tests"
      script:
        - docker exec -it txt_controller_cross_compiler bash -c 'cd /workspace/build/test_release ; ctest -V --exclude-regex ".*IntegrationTests.*"'
    - name: "Execute Integration Tests"
      script:
        - docker exec -it txt_controller_cross_compiler bash -c 'cd /workspace/build/test_release ; ctest -V --exclude-regex ".*IntegrationTests.*"'