version: '3'

services:
  toolchain:
    container_name: txt_controller_cross_compiler
    image: e6r4de7ly3x6ws3g/txt-controller-toolchain:latest
    volumes:
      - .:/workspace
    command: /bin/sh -c "while sleep 1000; do :; done"
